// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8VOj1ySALVy5drSXH49qrHSB1xTS8OV4',
    appId: '1:332404621943:web:3e1e3116807818c0b73c72',
    messagingSenderId: '332404621943',
    projectId: 'anpr-database-da01c',
    authDomain: 'anpr-database-da01c.firebaseapp.com',
    databaseURL: 'https://anpr-database-da01c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anpr-database-da01c.firebasestorage.app',
    measurementId: 'G-CQX9VMYM7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4ali8ij-kFRSi5Ah7J8h4Dqjc4sE9ds',
    appId: '1:332404621943:android:8adfe1245c043371b73c72',
    messagingSenderId: '332404621943',
    projectId: 'anpr-database-da01c',
    databaseURL: 'https://anpr-database-da01c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anpr-database-da01c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbh-cF2xIzlS-nTKbkRZ7iz6JXUgkjnS0',
    appId: '1:332404621943:ios:369627fb6df34096b73c72',
    messagingSenderId: '332404621943',
    projectId: 'anpr-database-da01c',
    databaseURL: 'https://anpr-database-da01c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anpr-database-da01c.firebasestorage.app',
    iosBundleId: 'com.example.anpr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbh-cF2xIzlS-nTKbkRZ7iz6JXUgkjnS0',
    appId: '1:332404621943:ios:369627fb6df34096b73c72',
    messagingSenderId: '332404621943',
    projectId: 'anpr-database-da01c',
    databaseURL: 'https://anpr-database-da01c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anpr-database-da01c.firebasestorage.app',
    iosBundleId: 'com.example.anpr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8VOj1ySALVy5drSXH49qrHSB1xTS8OV4',
    appId: '1:332404621943:web:4f58982347f875a1b73c72',
    messagingSenderId: '332404621943',
    projectId: 'anpr-database-da01c',
    authDomain: 'anpr-database-da01c.firebaseapp.com',
    databaseURL: 'https://anpr-database-da01c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anpr-database-da01c.firebasestorage.app',
    measurementId: 'G-XLEM1K9HMF',
  );

}